<?php

namespace CodeDelivery\Http\Controllers\Admin;

use CodeDelivery\Http\Controllers\Admin\Contracts\IUsersController;
use CodeDelivery\Http\Controllers\BetaGT\SimpleController;
use CodeDelivery\Http\Requests\Admin\UserRequest;
use CodeDelivery\Repositories\UserRepository;

class UsersController extends SimpleController implements IUsersController
{
    public function __construct(UserRepository $repository)
    {
        $this->repository = $repository;

        $this->titulo = 'Usuários do Sistema/Clientes';

        $this->template = 'admin.users';

        $this->route = $this->template;

        if (auth()->user()->role == 'estabelecimento')
            $this->route = 'cliente.users';
    }

    public function show($id)
    {
        if (auth()->user()->role == 'estabelecimento')
        {
            if (auth()->user()->id <> $id)
            {
                abort(500, 'Você não tem autorização para visualizar essas informações');
            }
            $this->route = 'cliente.users';
        }
        return parent::show($id); // TODO: Change the autogenerated stub
    }

    public function store(UserRequest $request)
    {
        try {
            $data = $request->all();

            $entity = $this->repository->create($data);

            return redirect()->route($this->route . '.show', [ 'id' => $entity->id ])->with('success', "Registro #{$entity->id} cadastrado com sucesso");
        }
        catch (\Exception $ex)
        {
            return redirect()->route($this->route . '.index')->with('warning', $ex->getMessage());
        }
    }

    public function update(UserRequest $request, $id)
    {
        try
        {
            $entity = $this->repository->find($id);

            $data = $request->all();

            $this->repository->update($data, $entity->id);

            return redirect()->route($this->route . '.show', [ 'id' => $entity->id ])->with('success', "O registro {$entity->id} foi atualizado com sucesso");
        }
        catch (\Exception $ex)
        {
            return redirect()->route($this->route . '.index')->with('warning', $ex->getMessage());
        }
    }
}