<?php

namespace CodeDelivery\Repositories;

use CodeDelivery\Presenters\UserPresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use CodeDelivery\Repositories\UserRepository;
use CodeDelivery\Models\User;
use CodeDelivery\Validators\UserValidator;

/**
 * Class UserRepositoryEloquent
 * @package namespace App\Repositories;
 */
class UserRepositoryEloquent extends BaseRepository implements UserRepository
{
    protected $skipPresenter = true;
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return User::class;
    }

    public function getDeliveryman(){
        return $this->model->where(['role'=>'deliveryman'])->lists('name','id');
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
    
    public function presenter()
    {
        return UserPresenter::class; // TODO: Change the autogenerated stub
    }
    
    public function updateDeviceToken($id, $devicetoken)
    {
        $model = $this->model->find($id);
        $model->device_token = $devicetoken;
        $model->save();
        return $this->parserResult($model);
    }

    public function updateFone($id, $telefoneCelular)
    {
        $model = $this->model->find($id);
        $model->telefone_celular = $telefoneCelular;
        $model->save();
        return $this->parserResult($model);
    }
}
